Phase3: Let's close some regions :D (`try_close()`)
fxpl/cpython pull request #31
Opened 2024-12-20 13:12 UTC by xFrednet

This adds the new `try_close()` function which *cleans* the LRC and OSC to see if the region can be closed. It returns `True` if the close was successful `False` otherwise.

The implementation roughly looks like this:
1. Merge the region into the local region
2. Move all objects reachable from the bridge object back into the region
3. Do the same for any sub-regions

Finally, check the LRC. It's expected to be 1 from the region being passed in as a function argument. Or 2 if the owning reference comes from the local region.

And that's basically it. I believe the implementation is mostly ready, I plan to add a lot more tests, including region internal cycles etc. That will probably also discover a few more bugs. But from my limited testing, it seems to work :D

2025-01-07 09:08 UTC, TobiasWrigstad approved these changes
Great work Fred! Let's merge!

2025-01-07 09:08 UTC, TobiasWrigstad commented on Lib/test/test_veronapy.py
> +        makeimmutable(type({}))
Dict type is immutable by default in the phase3 branch.

2025-01-07 09:08 UTC, TobiasWrigstad commented on Objects/cown.c
> +    BAIL_UNLESS_OWNED(self, "Attempt to get value of unacquired cown");
Why this name change? I think acquiring a cown has been the standard terminology.

2025-01-07 10:00 UTC, xFrednet commented on Objects/cown.c
> +    BAIL_UNLESS_OWNED(self, "Attempt to get value of unacquired cown");
The name remained the same, I changed the macro that is being used.

`BAIL_UNLESS_ACQUIRED` also required the state to be `ACQUIRED` this prevented me from accessing the region again and closing it via a function call. So, not a change in naming but in the prerequisites for this function. A maybe better alternative would be to have a `close` function on the cown.

2025-01-07 13:56 UTC, TobiasWrigstad commented on Objects/cown.c
> +    BAIL_UNLESS_OWNED(self, "Attempt to get value of unacquired cown");
Ah my bad! Great!

2025-01-07 15:39 UTC, xFrednet commented
I removed the `makeimmutable(type({}))`

I'll give @mjp41 a bit more time in case he wants to review as well :)

2025-01-08 10:38 UTC, mjp41 requested changes
LGTM, but I think a few comments would go a along way to improving readability.

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +        return 0;
Should this be called on a local or immutable region.   Could we error here?

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +static int regionmetadata_dec_rc(Py_region_ptr_t self_ptr)
Comment about return values would be helpful.

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +static int regionmetadata_dec_osc(Py_region_ptr_t self_ptr)
Comment about return values would be helpful.

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +static int regionmetadata_close(regionmetadata* self) {
Comment about return values would be helpful.

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +            goto fail;
Could this failure cause a leak or an inconsistent state?

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +                goto fail;
Could this failure cause a leak or an inconsistent state?

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +                goto fail;
Could this failure cause a leak or an inconsistent state?

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +static int try_close(PyRegionObject *root_bridge) {
I think a highlevel comment about the algorithm would be really helpful here.

2025-01-08 10:38 UTC, mjp41 commented on Objects/regions.c
> +        regionmetadata_inc_rc(new_data);
Is the inc here because of assigning the metadata?  Does this mean you also need a decref on the old data?  Or is that being transferred to the merge?  I think some comments on the RC usage here, or macros/functions to combine would be helpful for readability here.

2025-01-08 13:26 UTC, xFrednet commented on Objects/regions.c
> +            goto fail;
> Could this failure cause a leak

It shouldn't be (Besides the fact that the reference counting of the stack structure on failure has to be investigated at one point, as pointed out by the FIXME comment in line 519). But all memory should be reclaimed by the `fail:` code

> Could this failure cause an inconsistent state?

Yes, but the only error that can occur here is a `OutOfMemory` error. I don't believe we can correctly recover from that. The `MakeImmutable` code also just bails and leaves pointers from immutable objects to mutable ones.

In some sense this is actually safer, since we already set the region on the bridge object. So at worse, it would point from a region into another region. Which is "fine", while the region isn't closed. I'll make a small adjustment, to mark the region as dirty to make sure we don't trust the LRC, but it should be "fine" to leave it in this state.

2025-01-08 13:46 UTC, xFrednet commented on Objects/regions.c
> +            goto fail;
I've added a short comment in code and marked the region as dirty

2025-01-08 13:46 UTC, xFrednet commented on Objects/regions.c
> +                goto fail;
I've added a short comment in code and marked the region as dirty

2025-01-08 14:04 UTC, xFrednet commented on Objects/regions.c
> +                goto fail;
Added a comment

2025-01-08 14:10 UTC, xFrednet commented on Objects/regions.c
> +        regionmetadata_inc_rc(new_data);
Good catch, yeah pretty sure it needs to dec rc here

2025-01-08 14:22 UTC, xFrednet commented on Objects/regions.c
> +        regionmetadata_inc_rc(new_data);
And I also added comments

2025-01-08 14:33 UTC, xFrednet commented on Objects/regions.c
> +        return 0;
Yes, we could error here, but I found that every place I used this function also needed a `HAS_METADATA()` check. So having the check outside the function just spread several if statements around the codebase, while now it`s a nice `regionmetadata_dec_osc(region)` call.

So, we could error, but I don't really see an upside.

2025-01-08 14:34 UTC, xFrednet commented
@mjp41  All comments should be addressed

2025-01-08 17:21 UTC, mjp41 approved these changes
LGTM, thanks for adding the comments.

2025-01-08 17:21 UTC, mjp41 commented on Objects/regions.c
>          regionmetadata_set_parent(old_data, NULL);
Should `NULL` be the local region?

2025-01-09 09:36 UTC, xFrednet commented on Objects/regions.c
>          regionmetadata_set_parent(old_data, NULL);
As written on Teams, I prefer NULL to indicate that this clears the parent. But both are valid and behave the same.

2025-01-09 09:40 UTC, merged